### ISSUE TITLE
JOSS Review: General Comments

### ISSUE THREAD

**Issue by kbarnhart** [passaH2O/dorado#9]
From @dbuscombe-usgs's JOSS review [link to comment](https://github.com/openjournals/joss-reviews/issues/2585#issuecomment-692365791)

openjournals/joss-reviews/issues/2585

> What is the motivation for maintaining both pip and conda versions? Seems like picking one and ensuring support would be easier. Also, I suggest you recommend users make use of a virtual environment (venv) or conda environment to make installation, maintenance and compatibility with other projects easier.

> The demo on https://passah2o.github.io/dorado/quickstart/index.html#demo-1-using-the-high-level-api is missing:
“import matplotlib.pyplot as plt”
Also, please provide some higher level explanation for what this example is actually doing and what this is a simulation of.

> Are there any plans to add or change functionality in the future? If so, a roadmap would be a good addition. It would also be a good way for others could see themselves contributing

> Instead of using the future package, presumably to make things backwards-compatible, I would suggest catering ONLY to python 3 and later. This is a new program so backwards-compatibility is certainly not expected and probably not necessary.

**Comment by elbeejay** [comment]
We think we've addressed these concerns, and appreciate the suggestions. A point-by-point explanation of what has been done to handle each suggestion is below.

- We've dropped official support for the `conda` installation (which had it's own issues anyway) and are only recommending `pip` or installation from source. Our continuous integration ensures that all code merged into the 'master' branch installs, passes unit tests, and can run the examples on MacOS, Windows, and Linux running Python versions 2.7, 3.6, 3.7 and 3.8.

- We fixed the quickstart demo and tried to provide a bit more context as to what is happening and why someone might want to conduct a simulation like this

- While we welcome suggestions or additions to the codebase, we do not have a clear road map for future additions or functionality. But, thanks to your suggestions we have expanded upon our contribution guidelines to hopefully make contributing easier and more accessible to all.

- The primary reason we maintain Python 2.7 compatibility is so that this package can be used in the same environment as [Anuga](https://github.com/GeoscienceAustralia/anuga_core), which is the basis for many of our example cases, and is the hydrodynamic model some of our users are working with. Currently Anuga is still in Python 2.7 with incomplete support for 3.x.
